### ISSUE TITLE
Broken install on RedHat6.5 after argparse changes

### ISSUE THREAD

**Issue by kbeardmore** [genereese/togo#11]
./build-togo.sh

Checking build dependencies...

rpm-build-4.8.0-38.el6_6.x86_64
python-sqlobject-0.10.2-5.el6.noarch

Attempting to build the togo RPM...
Traceback (most recent call last):
  File "./root/usr/local/bin/togo", line 3, in <module>
    from argparse import RawTextHelpFormatter
ImportError: No module named argparse

**Comment by genereese** [comment]
This should be fixed now. Thanks for the bug report.
