### ISSUE TITLE
Suggestion: rsync as dependency

### ISSUE THREAD

**Issue by nmilosev** [genereese/togo#16]
Hi! First of all, great tool! I'm learning to package RPM's and this is a huge help.

When building against Fedora COPR Mock minimal chroot, the build fails because rsync isn't installed. This is obviously solved easily with ```BuildRequires: rsync```. 

Do you think it would be wise to add this by default?

Cheers!

**Comment by genereese** [comment]
Hah! Thanks for pointing that out, and my apologies for the delay in response; I've been very busy with work.

I've added the BuildRequires as suggested.

**Comment by nmilosev** [comment]
Thanks!
