### ISSUE TITLE
Bug: AutoReqProv not working

### ISSUE THREAD

**Issue by nmilosev** [genereese/togo#17]
In the default spec template ```# AutoReqProv: no``` is at the end of the file where it isn't working for me when setting it to false (no). It works if it is at the top before the first ```%``` statement, where I believe it should be by default.

Cheers!

**Comment by genereese** [comment]
Thanks for your input! That's been a long-standing bug and I had implemented a command-line workaround because I could never get AutoReqProv to actually function properly:

togo build package --nodeps

I've updated the spec template generation to move it further up so that it functions properly.

**Comment by nmilosev** [comment]
Thanks again!
