### ISSUE TITLE
Setting noreplace for config files

### ISSUE THREAD

**Issue by Tristanlogd** [genereese/togo#21]
Love the builder, I was using FPM but it doesn't give me a spec file, and I will need the actual spec file going forward with my packages and it looks like I can use the spec file Togo generates. 

My question was more centered around how to set the rpms config files, for example, setting %config(noreplace) on certain files. Is this something that is currently possible or something that can be added?

Thanks for the great work!

**Comment by Tristanlogd** [comment]
Looking deeper in the actual code of Togo, I figured it out! Awesome!! I think I will use this heavily as I really do not understand the RPM generation process and this is super easy!

**Comment by genereese** [comment]
Great; I'm glad you were able to locate the feature.

I'm considering trying to write up some more detailed documentation now that the software is a little more mature. I'll put it on my to-do list and see if I can address it in the near future.

Please let me know if you run into any issues.
