### ISSUE TITLE
Build source RPM

### ISSUE THREAD

**Issue by ChipwizBen** [genereese/togo#23]
Firstly, this software is really, really good. So thanks a lot, you've saved me a lot of time building RPMs.

I have a small feature request - I'd like to also be able to build source RPMs with this without having to edit your source before I run it. i.e.:

> exec_string = "time rpmbuild --define '_topdir %s' **-bb** %s" % (

to

> exec_string = "time rpmbuild --define '_topdir %s' **-ba** %s" % (

It would be nice if there were additional options to be able to generate a source RPM, such as:

- togo build package - current behaviour
- togo build source - build source RPM
- togo build all - builds both

**Comment by genereese** [comment]
Thank you for your kind words. Your request sounds reasonable; I should have some time to make the modifications over the weekend.

**Comment by genereese** [comment]
Just an update here; I had some flooding at my home and have been delayed in getting to this. I hope to tackle it soon.

**Comment by genereese** [comment]
I just wanted to let you know that I released a simplified update which should work for your needs. The source package is simply built along-side the RPM and is placed in ./rpms/src when 'togo build package' is run.

Until I have a chance to make some more elegant changes, I figured this was the best option.

**Comment by ChipwizBen** [comment]
Great, thanks a lot for your efforts.
