### ISSUE TITLE
build-togo.sh wants python-sqlobject that CentOS 6 doesn't have

### ISSUE THREAD

**Issue by vpithart** [genereese/togo#25]
According to quick start guide, running `./build-togo.sh`. It finds out `package python-sqlobject is not installed` but yum install says `No package python-sqlobject available.`

```
$ cat /etc/issue
CentOS release 6.9 (Final)
```
Is there ay alternative?

**Comment by genereese** [comment]
You can probably use pip to install the python module instead:

`sudo pip install SQLObject`

Then, as the build script says, manually run the RPM build using the togo script:

`./root/usr/bin/togo build package`

-from the root of your togo directory.
