### ISSUE TITLE
how to automatically generate the line containing date in changelog?

### ISSUE THREAD

**Issue by mailinglists35** [genereese/togo#29]
I can manually edit the `spec/changelog` file, is there an automated way togo can generate the date/email line for me when I want to add more entries other than the first autogenerated one?

**Comment by genereese** [comment]
Wow, just reviewing these issues; not sure why I was never notified about them.

If using vim, you could do something like this:

`:pu=strftime('* %a %b %d %Y Gene Reese <gene.reese@xirsix.com>')`

-but otherwise, I don't know of an easier way.

**Comment by mailinglists35** [comment]
heh, I was looking for a feature in the software that would automatically insert that line. else I specified it can be inserted by the user. but the feature request is to be inserted automatically by togo...
