### ISSUE TITLE
RHEL 8 / CentOS 8 support

### ISSUE THREAD

**Issue by stevemeier** [genereese/togo#35]
Hello,

with CentOS 8 now released I wanted to start packaging on it using `togo`.
To get it to run I had to make a handful of changes:

`python` needs to be changed to `python2` as both, 2.7 and 3.6 are provided.
There is no RPM for the sqlobject module in EPEL 8, so you have to install it using `pip2 install sqlobject` (includes two dependencies).

After these changes `togo` seems to run fine.

**Comment by siscia** [comment]
Many thank!

Indeed togo for CentOS8 would be useful.

**Comment by genereese** [comment]
Thanks for the report; I'm trying to budget some time to address this and hope to have something by the end of the weekend.

It may be time to simply change Togo over to python3 anyway.

**Comment by genereese** [comment]
Decided to stick with python2 for now since I don't have time to perform a thorough update at the moment.

Please give the new release a try and let me know if I overlooked anything.

**Comment by liedekef** [comment]
If you want: I've created a version of togo that works for both python2 and python3 (and resolves 2 open tickets too)

**Comment by siscia** [comment]
It would be wonderful if we could reach a solution.

The best case scenario it would be something that we can install on RHEL8 / Centos8 directly from github or with some RPM.

I got a little bit of time, let me work on this a tiny bit and see if I can come out with a reasonable solution.

**Comment by siscia** [comment]
So the biggest problem seems to be the dependencies on SQLObject.

**Comment by liedekef** [comment]
See my version: https://github.com/liedekef/togo

**Comment by siscia** [comment]
@liedekef I see it, but I wasn't really convinced by the bash hijack.

To be honest I didn't understand it, so it may as well be much better than my solution and a more common practices.

In my version I tried to don't touch the code but only the environment around it.
