### ISSUE TITLE
Updating SymLink

### ISSUE THREAD

**Issue by wakil1** [genereese/togo#41]
Hello, 

When I simulate an update, by installing 3.5.5 and then installing 3.6.3; the expected is that it removes the symlink that 3.5.5 created during uninstall of 3.5.5, and creates one during the install of 3.6.3, but thats not whats happening. I tried playing around with deleting information on preun and postun but that was not helping. Any ideas would be awesome.

Thanks

**Comment by genereese** [comment]
It looks like this is potentially a long-standing issue with RPM. Here's a post from 6 years ago regarding the same thing:

https://stackoverflow.com/questions/33747041/create-symlink-in-rpm

Is there a specific reason you're not creating the symlink in the togo root directory before you build the package? If you create it there, RPM should handle the installation/removal of the symlink when you perform the upgrade.

**Comment by genereese** [comment]
Going ahead and closing this issue.
