### ISSUE TITLE
Installed (but unpackaged) file(s) found

### ISSUE THREAD

**Issue by cmtm** [genereese/togo#42]
I'm getting the following failure when running `togo build package`:

```
Processing files: [REDACTED].noarch
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/[REDACTED]/meta/redhat/BUILDROOT/[REDACTED].x86_64
error: Installed (but unpackaged) file(s) found:
   /.package_note-[REDACTED].x86_64.ld

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /.package_note-[REDACTED].x86_64.ld
```

**Comment by cmtm** [comment]
I added `%undefine _package_note_file` to the `spec/header` file and this issue no longer occurs.

**Comment by genereese** [comment]
Togo should include that file automatically unless it is created during the build process by whatever method you may be using to build your package (outside of Togo's automation). If that's the case, then rpmbuild will fail as the file is not included in the %files list that Togo automatically generates in the spec file.

If you need that generated file, you can work around this by having togo build the spec file:

`togo build spec`

-then edit the "generated.spec" file and add the missing file to the %files (at the bottom of the spec file). Then save and build the package referencing your modified spec file:

`togo build package -s generated.spec`
