### ISSUE TITLE
togo -f parameter

### ISSUE THREAD

**Issue by retuxx** [genereese/togo#5]
It would be useful to add an option to 'togo -f' which allows to give the flag as parameter. I need this for scripting.

**Comment by genereese** [comment]
Hey Marcel,

Thanks for the suggestion... I'll see if I can add in that option later
this evening.

Please let me know if you have any additional comments or concerns.

Regards,

Gene Reese
Managing Partner
Xirsix
gene.reese@xirsix.com

**Comment by retuxx** [comment]
First things first. You did a great job with togo and I'm going to use it for my projects now. Keep it up!

> Please let me know if you have any additional comments or concerns.

There is one more thing. Togo asks the user for his username and email on first run. This 'feature' is not very useful when using scripts for automated packaging. I give you an example:

I added the current version of togo into my repository to use it for automated packaging. Furthermore I have a script controlling togo. While creating the togo project it asks me (or any user running the script) for the username and email on first run. Since I run togo before there is no problem. But other user creating the rpm have to fill in the values for no reason, because I patch the header spec later in the script anyway (I just override the created specs with my own).

I think togo should provide an execution trace without any interactive steps. I think the easiest solution for this is to remove this feature. If an user did not configured its togo instance by using togo --configure the username and email should be something like: unkown <unknown@unkonwn.com>. You could print a warning message on output to give an advise. Adding parameters for this usecase may complicate the usage of togo and I think the simpleness is its strength.

**Comment by retuxx** [comment]
Ping, any progress here?

**Comment by genereese** [comment]
Hi Marcel,

Sorry, no. My company is opening a new facility and we've been on a tight
timeline. I haven't forgotten about you though, I promise. I'll give you an
update as soon as I'm able to.

Please let me know if you have any additional comments or concerns.

Regards,

Gene Reese
Managing Partner
Xirsix
gene.reese@xirsix.com

**Comment by genereese** [comment]
Just a note here; updated Togo to remove the automatic prompting of the user's name and email address on the first run. Working on the flags now.

**Comment by retuxx** [comment]
> Just a note here; updated Togo to remove the automatic prompting of the user's name and email address on the first run.

Thats cool, thanks!

**Comment by genereese** [comment]
> It would be useful to add an option to 'togo -f' which allows to give the flag as parameter. I need this > for scripting.

Just an update:
I've decided to release this as a feature Togo 2.0. I'm going to do a major overhaul on the file flagging system (which will, unfortunately, not be backwards compatible with Togo 1.x).

What are currently known as 'file flags' in Togo will be renamed to 'directives' (which is the official RPM terminology). I will also be adding file attributes (the ability to set file modes and permissions on RPM-installed files).

Also, the interactive file flagging system that is currently in Togo will be gone - all file tagging will be done directly via the command line.

Lastly, I will be replacing optparse with argparse (as optparse was deprecated in python 2.7).

**Comment by genereese** [comment]
I just pushed out Togo 2.0 which now has this enhancement. Please check the readme for the syntax changes. I will have the new documentation up regarding the added features, shortly.

Please also be aware that if you are running Togo 2.x against a project created with Togo 1.x, you will need to re-initialize the file database with:

togo file database --init

Unfortunately, you will also need to re-flag your files and excludes after you do this.

File attributes are not available yet, but they are coming in the next update.
