### ISSUE TITLE
I spy Grover

### ISSUE THREAD

**Issue by bhyde** [genereese/togo#6]
![image](https://cloud.githubusercontent.com/assets/19701/6073133/35de2cae-ad78-11e4-8816-16f06a4783f8.png)

https://github.com/genereese/togo/blob/master/root/usr/local/bin/togo#L145

**Comment by genereese** [comment]
Hah! Thanks for catching that. I must have accidentally pasted something
from an article I was reading or something.

Please let me know if you have any additional comments or concerns.

Regards,

Gene Reese
Managing Partner
Xirsix
gene.reese@xirsix.com
