### ISSUE TITLE
Added files to root go unnoticed

### ISSUE THREAD

**Issue by bhyde** [genereese/togo#7]
No doubt I'm doing something wrong, but I added some files to root, and when I built the RPM they weren't included.

Before the change I had no files in root/etc; after the change I'd added root/etc/sudoers and some other things.  I then ran togo again and the resulting RPM did not contain my additions.

I worked around his by recreating the entire project, but that seems like a very big and tedious approach.  

I recreated it by moving the project, creating it again, and then selectively moving things back.  So maybe there is a less tedious way to recreate it?

Meanwhile, and unrelated.  I've since learned that root/etc/sudoers is owned by another RPM and it's inappropriate for my RPM to try to own it as well.  There is a interesting slide deck about RPMs v.s. config. files [here](http://www.redhat.com/promo/summit/2010/presentations/summit/opensource-for-it-leaders/thurs/pwaterma-2-rpm/RPM-ifying-System-Configurations.pdf), and some confusing additional details [here](http://www-uxsup.csx.cam.ac.uk/~jw35/docs/rpm_config.html).

**Comment by genereese** [comment]
Hi there. I'm sorry this response is so delayed; I've been very busy with my job.

It sounds like you simply weren't adding the new file(s) with 'togo -a <filename>' to the existing project. If you do not add the files to the project's database using the 'togo -a' command, the rpmbuild will not know to include the files in the actual RPM; it will assume you did not want them as part of the final RPM package.

**Comment by genereese** [comment]
Terribly sorry; I prematurely left an answer here for a development version of the project. Give me a few and I'll update you further.

**Comment by genereese** [comment]
Well, after some testing, I can't seem to reproduce the problem. Would you be able to give me the exact steps to reproduce the error?

**Comment by genereese** [comment]
Going to go ahead and close this issue. If you're still having problems, please open a new issue and I'll look into it.
